title: Saifas-ssg-jekyll-app-abc
email: jekyll@saifas.info
description: Simple application with jekyll-saifas-theme
author:
  name: SAIFAS
copyright: © SAIFAS
version: 0.1.0
lang: en_US
about: Jekyll theme SAIFAS IT
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: jekyll-theme-saifas
plugins:
  - jekyll-feed

contents_root_path: /contents/
contents_pages_path: /contents/pages/

source: ./

destination: ../app-build-static

layouts_dir: ./templates/_layouts/

layout:
  footer:
    contact_us: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/